spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safer
    username: postgres
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

appKey: ${TMAP_APP_KEY}