spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safer
    username: root
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false
